# Generated by Django 4.1.7 on 2023-04-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Traduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre_original", models.CharField(max_length=200)),
                ("titre_anglais", models.CharField(max_length=200)),
                ("titre_français", models.CharField(max_length=200)),
            ],
        ),
    ]
