# Generated by Django 4.1.7 on 2023-04-12 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product_category_name_translation",
            fields=[
                (
                    "product_category_name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("product_category_name_english", models.CharField(max_length=200)),
                ("product_category_name_french", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product_category_name_translation",
            },
        ),
        migrations.DeleteModel(
            name="Traduction",
        ),
    ]
